name = "sentinel-introducer"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[durable_objects.bindings]]
name = "SERVERS"
class_name = "Server"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Server"]

[[durable_objects.bindings]]
name = "RELAYS"
class_name = "Relay"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Relay"]
